package launchd

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"github.com/titusmd/vaultmount/internal/config"
)

const plistTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{{.Label}}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{{.ScriptPath}}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StartInterval</key>
    <integer>{{.Interval}}</integer>
    <key>StandardOutPath</key>
    <string>{{.LogPath}}</string>
    <key>StandardErrorPath</key>
    <string>{{.LogPath}}</string>
</dict>
</plist>
`

const mountScriptTemplate = `#!/usr/bin/env bash
# vaultmount — deterministic SSHFS mount for {{.Name}}
# Generated by vaultmount. Do not edit manually.
set -uo pipefail

MOUNT_POINT="{{.MountPoint}}"
VPS_HOST="{{.User}}@{{.Host}}"
VPS_PATH="{{.RemotePath}}"
SSHFS_BIN="{{.SSHFSBin}}"
LOG="{{.LogPath}}"
LOCK="/tmp/vaultmount-{{.ID}}.lock"
MAX_RETRIES=3
RETRY_DELAY=5
SSH_TIMEOUT=5

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

log()   { printf '%s [%-5s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$1" "$2" >> "$LOG"; }
info()  { log INFO  "$1"; }
warn()  { log WARN  "$1"; }
error() { log ERROR "$1"; }
fatal() { log FATAL "$1"; }

# Concurrency guard
if [[ -f "$LOCK" ]]; then
  lpid=$(cat "$LOCK" 2>/dev/null)
  if kill -0 "$lpid" 2>/dev/null; then
    info "Already running (pid $lpid) — skip"; exit 0
  fi
  warn "Stale lock (pid $lpid) — removing"
  rm -f "$LOCK"
fi
echo $$ > "$LOCK"
trap 'rm -f "$LOCK"' EXIT INT TERM HUP

info "══════ Mount check (pid $$) ══════"

# Check if already mounted and alive
if mount 2>/dev/null | grep -q "$MOUNT_POINT"; then
  if /bin/ls "$MOUNT_POINT" &>/dev/null; then
    info "Mount healthy — done"; exit 0
  else
    warn "Dead mount detected — force unmounting"
    diskutil unmount force "$MOUNT_POINT" >> "$LOG" 2>&1 || umount -f "$MOUNT_POINT" >> "$LOG" 2>&1 || true
    sleep 1
  fi
fi

mkdir -p "$MOUNT_POINT" || { fatal "Cannot create mount point $MOUNT_POINT"; exit 1; }

# macFUSE check — uses system_profiler (arm64 dext-aware, not kextstat which is legacy)
sp_loaded=$(system_profiler SPExtensionsDataType 2>/dev/null | awk '/macFUSE/{found=1} found && /Loaded:/{print $2; exit}')
if [[ "$sp_loaded" != "Yes" ]]; then
  fatal "macFUSE driver not loaded — reboot may fix"; exit 1
fi
info "macFUSE driver loaded"

# sshfs binary check
if [[ ! -x "$SSHFS_BIN" ]]; then
  fatal "sshfs binary missing at $SSHFS_BIN"; exit 1
fi

# VPS connectivity check
ssh_out=$(ssh -o BatchMode=yes -o ConnectTimeout=$SSH_TIMEOUT \
              -o StrictHostKeyChecking=yes \
              {{- if .SSHKeyPath}} -i "{{.SSHKeyPath}}"{{end}} \
              -p {{.Port}} "$VPS_HOST" exit 2>&1)
ssh_code=$?
if (( ssh_code != 0 )); then
  if echo "$ssh_out" | grep -qiE 'IDENTIFICATION HAS CHANGED|Host key verification'; then
    fatal "HOST KEY CHANGED — fix: ssh-keygen -R {{.Host}}"; exit 1
  fi
  if echo "$ssh_out" | grep -qiE 'Permission denied|publickey|authentication'; then
    fatal "SSH auth rejected — check key setup"; exit 1
  fi
  warn "VPS unreachable — deferring to next cycle"
  exit 0
fi
info "VPS SSH OK"

# Mount with retries
SSHFS_OPTS=(
  reconnect
  ServerAliveInterval=15
  ServerAliveCountMax=3
  follow_symlinks
  "volname={{.Name}}"
  auto_cache
  {{- if .Compression}}
  Compression=yes
  {{- else}}
  Compression=no
  {{- end}}
  {{- if .SSHKeyPath}}
  "IdentityFile={{.SSHKeyPath}}"
  {{- end}}
  "port={{.Port}}"
)

for attempt in $(seq 1 $MAX_RETRIES); do
  info "Attempt $attempt/$MAX_RETRIES"
  sshfs_args=()
  for opt in "${SSHFS_OPTS[@]}"; do
    sshfs_args+=("-o" "$opt")
  done
  "$SSHFS_BIN" "${VPS_HOST}:${VPS_PATH}" "$MOUNT_POINT" "${sshfs_args[@]}" >> "$LOG" 2>&1
  code=$?
  if (( code != 0 )); then
    warn "sshfs exited $code"
    (( attempt < MAX_RETRIES )) && sleep "$RETRY_DELAY" && continue
    error "All $MAX_RETRIES attempts failed"; exit 1
  fi
  sleep 2
  if mount 2>/dev/null | grep -q "$MOUNT_POINT"; then
    info "══════ Mount succeeded ══════"; exit 0
  fi
  fatal "sshfs exited 0 but not in mount table — macFUSE driver failure (reboot to fix)"
  exit 1
done
`

// PlistConfig holds parameters for plist generation.
type PlistConfig struct {
	Label      string
	ScriptPath string
	Interval   int
	LogPath    string
}

// Generate returns the XML plist content.
func Generate(cfg PlistConfig) (string, error) {
	if cfg.Interval == 0 {
		cfg.Interval = 60
	}
	tmpl, err := template.New("plist").Parse(plistTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// ScriptConfig holds parameters for mount script generation.
type ScriptConfig struct {
	config.Connection
	SSHFSBin string
	LogPath  string
}

// GenerateMountScript returns the bash mount script content.
func GenerateMountScript(c config.Connection, sshfsBin, logPath string) (string, error) {
	sc := struct {
		config.Connection
		SSHFSBin string
		LogPath  string
	}{c, sshfsBin, logPath}

	tmpl, err := template.New("script").Parse(mountScriptTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, sc); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// launchAgentsDir is overridable for testing.
var launchAgentsDir = func() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, "Library", "LaunchAgents")
}

// Install writes the plist to ~/Library/LaunchAgents and loads it via launchctl.
func Install(cfg PlistConfig) error {
	return InstallTo(launchAgentsDir(), cfg)
}

// InstallTo writes the plist to the given directory (for testing).
func InstallTo(dir string, cfg PlistConfig) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create LaunchAgents dir: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(cfg.LogPath), 0o755); err != nil {
		return fmt.Errorf("create log dir: %w", err)
	}

	content, err := Generate(cfg)
	if err != nil {
		return err
	}

	plistPath := filepath.Join(dir, cfg.Label+".plist")
	if err := os.WriteFile(plistPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write plist: %w", err)
	}

	// Only load via launchctl when using real dir
	if dir == launchAgentsDir() {
		_ = exec.Command("launchctl", "unload", plistPath).Run()
		if out, err := exec.Command("launchctl", "load", plistPath).CombinedOutput(); err != nil {
			return fmt.Errorf("launchctl load: %w — %s", err, string(out))
		}
	}
	return nil
}

// Uninstall unloads and removes the plist.
func Uninstall(label string) error {
	return UninstallFrom(launchAgentsDir(), label)
}

// UninstallFrom unloads and removes from the given directory (for testing).
func UninstallFrom(dir, label string) error {
	plistPath := filepath.Join(dir, label+".plist")

	if dir == launchAgentsDir() {
		_ = exec.Command("launchctl", "unload", plistPath).Run()
	}

	if err := os.Remove(plistPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove plist: %w", err)
	}
	return nil
}

// IsInstalled returns true if the plist file exists in LaunchAgents.
func IsInstalled(label string) bool {
	plistPath := filepath.Join(launchAgentsDir(), label+".plist")
	_, err := os.Stat(plistPath)
	return err == nil
}

// Status returns the launchd status of the label via launchctl list.
func Status(label string) (loaded bool, pid int, err error) {
	out, err := exec.Command("launchctl", "list", label).CombinedOutput()
	if err != nil {
		return false, 0, nil // not loaded
	}
	lines := strings.Split(string(out), "\n")
	for _, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "\"PID\"") {
			parts := strings.Fields(line)
			if len(parts) >= 3 {
				pid, _ = strconv.Atoi(strings.Trim(parts[2], "\",;"))
			}
		}
	}
	return true, pid, nil
}
